name: clansv2
version: '1.0-SNAPSHOT'
main: org.quintilis.clansv2.Clansv2
api-version: '1.21'
commands:
  clan:
    description: "Comando principal de clã, para ver os usos é so escrever /clan"
    usage: /clan
  ally:
    description: "Comando para alianças entre clãs, para ver os usos é so escrever /ally"
    usage: /ally
  enemy:
    description: "Comando para inimigos §4MORTAIS§f, para ver os usos é so escrever /enemy"
    usage: /enemy
  war:
    description: "Comando para §4DECLARAR GUERRA§f, para ver os usos é so escrever /war"
    usage: /war
  invite:
    description: "Comando para aceitar ou rejeitar pedidos de junção a clãs, para ver os usos é só escrever /invite"
    usage: /invite